In [80]:
import pandas as pd
import numpy as np
import re

En este notebook voy a terminar de procesar todas las columnas de los dataframes y descripciones obtenidas en los notebooks anteriores, para dejar los dataframes listos para el EDA.

# Glassdoor

In [81]:
descripciones_glassdoor = pd.read_json('../data/interim/extracion_descripcion.jsonl', lines=True)
df_glassdoor = pd.read_csv('../data/raw/glassdoor.csv')

In [82]:
descripciones_glassdoor = descripciones_glassdoor.datos.apply(pd.Series)

In [83]:
descripciones_glassdoor.head(10)

,años_experiencia,experiencia,modalidad,habilidades,formación_académica,salario_minimo,salario_maximo,sector,ciudad,tipo_de_empleo,beneficios
0,3.0,junior,Presencial,"Fisioterapia neurológica, habilidades de comun...",Grado Universitario,24000.0,26000.0,"Salud, Farmacia y Tecnología Médica",Madrid,Media jornada,NaN
1,2.0,junior,Presencial,"Comercialización, trabajo en equipo, habilidad...",Ninguna,14400.0,72000.0,Servicios,Madrid,Jornada completa,NaN
2,1.0,junior,Presencial,"Profesor, enseñanza, habilidades de comunicaci...",Grado Universitario,12000.0,14400.0,Economía y política,Madrid,Jornada completa,NaN
3,3.0,senior,None,"Piloto, experiencia en Airbus FBW Wide Body, I...",Ninguna,131112.0,NaN,Transporte y Logística,Ávila,None,NaN
4,0.0,intern,Presencial,"comunicación, empatía, atención al cliente, ca...",Ninguna,15120.0,15168.0,Economía y política,Madrid,Jornada completa,NaN
5,NaN,None,None,"Experiencia en Salud y Seguridad Ocupacional, ...",Grado Universitario,NaN,NaN,Tecnología y telecomunicaciones,None,None,NaN
6,0.0,intern,None,"Desarrollo de actividades comerciales, captaci...",Ninguna,15000.0,15000.0,Internet,Madrid,Jornada completa,NaN
7,3.0,senior,Presencial,"Solving complex client problems, driving devel...",Grado Universitario,NaN,NaN,Agricultura,Valencia,Prácticas,NaN
8,1.0,junior,Presencial,"Bilingüe, nivel alto de inglés, preparación y ...",Ninguna,12000.0,12000.0,Economía y política,Madrid,Media jornada,NaN
9,NaN,None,Presencial,"Fisioterapia neurológica, habilidades de comun...",Ninguna,NaN,NaN,"Salud, Farmacia y Tecnología Médica",None,Media jornada,NaN


In [84]:
df_glassdoor.head(10)

,Titulo,Empresa,Localizacion,Salario,Fecha_Publicacion,Valoracion_Empresa,Descripcion_Completa,Busqueda_Ciudad,Busqueda_Puesto,Sector
0,FISIOTERAPEUTA NEUROLÓGICO,Centro Monte del Pilar,Madrid,24 mil € - 26 mil € (Proporcionado por la empr...,24 horas,"3,9",Oferta de empleo – Fisioterapeuta Neurológico/...,Madrid,Todos,NaN
1,Comercial puerta fría (presencial) - Sector ba...,Total Management Consulting,Madrid,1 mil € - 6 mil € (Proporcionado por la empresa),24 horas,"3,9",Desde Total Management Consulting nos encontra...,Madrid,Todos,NaN
2,Profesora/a de Lengua 2ºESO (Aravaca),Verona Servicios de Intermediación Educativa S.L.,Madrid,"10,00 € - 12,00 € Por hora (Proporcionado por ...",24 horas,"3,9",Estamos seleccionando un profesor/a para impar...,Madrid,Todos,NaN
3,Direct Entry Captain - Pilot,The Emirates Group,Madrid,No especificado,+ 30 d,"3,9",Company Introduction\r\n\r\n\r\nFrom its globa...,Madrid,Todos,NaN
4,Promotor/a - Encuestador/a de Educación (Campu...,Cambridge Exams,Madrid,1 mil € (Proporcionado por la empresa),24 horas,"3,9","¿Te consideras una persona extrovertida, empát...",Madrid,Todos,NaN
5,Health and Safety Specialist,Just Eat Takeaway.com,Madrid,No especificado,+ 30 d,"3,9",Ready for a challenge?\r\n\r\nThen Just Eat Ta...,Madrid,Todos,NaN
6,Únete a nuestro equipo: buscamos Asesores Inmo...,Gruppo Tempocasa,Madrid,1 mil € (Proporcionado por la empresa),23 días,"3,9","Tempocasa, empresa líder en el sector inmobili...",Madrid,Todos,NaN
7,Manager - BCG Vantage - Aerospace and Defense,Boston Consulting Group,Madrid,No especificado,+ 30 d,"3,9",Locations: Düsseldorf | München | London | Mad...,Madrid,Todos,NaN
8,PROFESOR/A DE BIOLOGÍA Y QUÍMICA BILINGÜE,Omid Holdings SL,Madrid,No especificado,+ 30 d,"3,9",We are looking for a teacher who can teach Bio...,Madrid,Todos,NaN
9,Fisioterapeuta en Leganés,Consultorio Medico Zarzaquemada,Madrid,No especificado,+ 30 d,"3,9","Fisioterapeuta se necesita, para clínica en fu...",Madrid,Todos,NaN


In [85]:
df_glassdoor.shape, descripciones_glassdoor.shape

((21069, 10), (21069, 11))

In [86]:
df_glassdoor_procesado = pd.concat([df_glassdoor, descripciones_glassdoor], axis=1)

In [87]:
df_glassdoor_procesado.head()

,Titulo,Empresa,Localizacion,Salario,Fecha_Publicacion,Valoracion_Empresa,Descripcion_Completa,Busqueda_Ciudad,Busqueda_Puesto,Sector,...,experiencia,modalidad,habilidades,formación_académica,salario_minimo,salario_maximo,sector,ciudad,tipo_de_empleo,beneficios
0,FISIOTERAPEUTA NEUROLÓGICO,Centro Monte del Pilar,Madrid,24 mil € - 26 mil € (Proporcionado por la empr...,24 horas,"3,9",Oferta de empleo – Fisioterapeuta Neurológico/...,Madrid,Todos,NaN,...,junior,Presencial,"Fisioterapia neurológica, habilidades de comun...",Grado Universitario,24000.0,26000.0,"Salud, Farmacia y Tecnología Médica",Madrid,Media jornada,NaN
1,Comercial puerta fría (presencial) - Sector ba...,Total Management Consulting,Madrid,1 mil € - 6 mil € (Proporcionado por la empresa),24 horas,"3,9",Desde Total Management Consulting nos encontra...,Madrid,Todos,NaN,...,junior,Presencial,"Comercialización, trabajo en equipo, habilidad...",Ninguna,14400.0,72000.0,Servicios,Madrid,Jornada completa,NaN
2,Profesora/a de Lengua 2ºESO (Aravaca),Verona Servicios de Intermediación Educativa S.L.,Madrid,"10,00 € - 12,00 € Por hora (Proporcionado por ...",24 horas,"3,9",Estamos seleccionando un profesor/a para impar...,Madrid,Todos,NaN,...,junior,Presencial,"Profesor, enseñanza, habilidades de comunicaci...",Grado Universitario,12000.0,14400.0,Economía y política,Madrid,Jornada completa,NaN
3,Direct Entry Captain - Pilot,The Emirates Group,Madrid,No especificado,+ 30 d,"3,9",Company Introduction\r\n\r\n\r\nFrom its globa...,Madrid,Todos,NaN,...,senior,None,"Piloto, experiencia en Airbus FBW Wide Body, I...",Ninguna,131112.0,NaN,Transporte y Logística,Ávila,None,NaN
4,Promotor/a - Encuestador/a de Educación (Campu...,Cambridge Exams,Madrid,1 mil € (Proporcionado por la empresa),24 horas,"3,9","¿Te consideras una persona extrovertida, empát...",Madrid,Todos,NaN,...,intern,Presencial,"comunicación, empatía, atención al cliente, ca...",Ninguna,15120.0,15168.0,Economía y política,Madrid,Jornada completa,NaN


In [88]:
df_glassdoor_procesado.columns

Index(['Titulo', 'Empresa', 'Localizacion', 'Salario', 'Fecha_Publicacion',
       'Valoracion_Empresa', 'Descripcion_Completa', 'Busqueda_Ciudad',
       'Busqueda_Puesto', 'Sector', 'años_experiencia', 'experiencia',
       'modalidad', 'habilidades', 'formación_académica', 'salario_minimo',
       'salario_maximo', 'sector', 'ciudad', 'tipo_de_empleo', 'beneficios'],
      dtype='object')

Voy a eliminar las columnas innecesarias: Empresa, Fecha_Publicacion, Valoracion_Empresa,Descripcion_Completa, Busqueda_Puesto, Sector

In [89]:
df_glassdoor_procesado.drop(columns=['Empresa', 'Salario', 'Fecha_Publicacion', 'Valoracion_Empresa','Descripcion_Completa', 'Busqueda_Puesto', 'Sector'], inplace=True)

### Ciudad

Para los registros donde tengo la ciudad en el dataframe de Glassdoor voy a priorizar ese valor frente al dado por la descripción y el procesamiento del LLM.

In [90]:
df_glassdoor_procesado['Ciudad'] = df_glassdoor_procesado.apply(lambda row: row['Busqueda_Ciudad'] if row['Busqueda_Ciudad'] != 'Todas' else row['ciudad'], axis=1)

In [91]:
df_glassdoor_procesado['Ciudad'] = df_glassdoor_procesado.apply(lambda row: row['Busqueda_Ciudad'] if row['Busqueda_Ciudad'] != 'Todas' else row['ciudad'], axis=1)

In [92]:
df_glassdoor_procesado[['Busqueda_Ciudad','ciudad','Ciudad']].head(10)

,Busqueda_Ciudad,ciudad,Ciudad
0,Madrid,Madrid,Madrid
1,Madrid,Madrid,Madrid
2,Madrid,Madrid,Madrid
3,Madrid,Ávila,Madrid
4,Madrid,Madrid,Madrid
5,Madrid,None,Madrid
6,Madrid,Madrid,Madrid
7,Madrid,Valencia,Madrid
8,Madrid,Madrid,Madrid
9,Madrid,None,Madrid


In [93]:
df_glassdoor_procesado.drop(columns=['Localizacion','Busqueda_Ciudad','ciudad'], inplace=True)

In [94]:
df_glassdoor_procesado['Ciudad'] = df_glassdoor_procesado['Ciudad'].fillna('España')

In [95]:
df_glassdoor_procesado['Ciudad'].value_counts()

Ciudad
España                        2238
Madrid                        1437
Barcelona                      997
Málaga                         539
Sevilla                        536
Pamplona                       534
Tarragona                      527
Pontevedra                     520
Logroño                        519
Santa Cruz de Tenerife         518
Gijón                          515
Toledo                         513
Murcia                         508
Girona                         507
Palma de Mallorca              501
Alicante                       494
Vigo                           487
Santander                      471
Valencia                       470
Almería                        458
Zaragoza                       452
Castellón de la Plana          435
Bilbao                         364
Huesca                         357
Córdoba                        353
Badajoz                        338
Jerez de la Frontera           336
Jaén                           301
Albacete     

In [96]:
df_glassdoor_procesado.head()

,Titulo,años_experiencia,experiencia,modalidad,habilidades,formación_académica,salario_minimo,salario_maximo,sector,tipo_de_empleo,beneficios,Ciudad
0,FISIOTERAPEUTA NEUROLÓGICO,3.0,junior,Presencial,"Fisioterapia neurológica, habilidades de comun...",Grado Universitario,24000.0,26000.0,"Salud, Farmacia y Tecnología Médica",Media jornada,NaN,Madrid
1,Comercial puerta fría (presencial) - Sector ba...,2.0,junior,Presencial,"Comercialización, trabajo en equipo, habilidad...",Ninguna,14400.0,72000.0,Servicios,Jornada completa,NaN,Madrid
2,Profesora/a de Lengua 2ºESO (Aravaca),1.0,junior,Presencial,"Profesor, enseñanza, habilidades de comunicaci...",Grado Universitario,12000.0,14400.0,Economía y política,Jornada completa,NaN,Madrid
3,Direct Entry Captain - Pilot,3.0,senior,None,"Piloto, experiencia en Airbus FBW Wide Body, I...",Ninguna,131112.0,NaN,Transporte y Logística,None,NaN,Madrid
4,Promotor/a - Encuestador/a de Educación (Campu...,0.0,intern,Presencial,"comunicación, empatía, atención al cliente, ca...",Ninguna,15120.0,15168.0,Economía y política,Jornada completa,NaN,Madrid


### Salario

In [97]:
df_glassdoor_procesado[['salario_minimo','salario_maximo']].head(10)

,salario_minimo,salario_maximo
0,24000.0,26000.0
1,14400.0,72000.0
2,12000.0,14400.0
3,131112.0,NaN
4,15120.0,15168.0
5,NaN,NaN
6,15000.0,15000.0
7,NaN,NaN
8,12000.0,12000.0
9,NaN,NaN


Voy a poner el mismo salario minimo y máximo para las filas donde hay un valor nulo en una de las columnas y en la otra no.

In [98]:
df_glassdoor_procesado['salario_minimo'] = df_glassdoor_procesado['salario_minimo'].fillna(df_glassdoor_procesado['salario_maximo'])
df_glassdoor_procesado['salario_maximo'] = df_glassdoor_procesado['salario_maximo'].fillna(df_glassdoor_procesado['salario_minimo'])

In [99]:
df_glassdoor_procesado[['salario_minimo','salario_maximo']].head(10)

,salario_minimo,salario_maximo
0,24000.0,26000.0
1,14400.0,72000.0
2,12000.0,14400.0
3,131112.0,131112.0
4,15120.0,15168.0
5,NaN,NaN
6,15000.0,15000.0
7,NaN,NaN
8,12000.0,12000.0
9,NaN,NaN


Ahora voy a comprobar si hay algun salario máximo inferior al salario minimo

In [100]:
df_prueba = df_glassdoor_procesado.copy()
df_prueba['Comprobacion_salario'] = df_prueba['salario_maximo'] - df_prueba['salario_minimo']

In [101]:
(df_prueba['Comprobacion_salario'] < 0).sum()

10

In [102]:
df_prueba[['salario_maximo','salario_minimo','Comprobacion_salario']][df_prueba['Comprobacion_salario'] < 0]

,salario_maximo,salario_minimo,Comprobacion_salario
1660,10200.00,10560.00,-360.00
1729,19800.24,22292.28,-2492.04
1787,19800.24,22292.28,-2492.04
1815,19800.24,22292.28,-2492.04
1818,19800.24,22292.28,-2492.04
1826,19290.12,22292.28,-3002.16
1955,1650.02,1857.69,-207.67
6577,27600.00,28800.00,-1200.00
16861,14868.00,16572.00,-1704.00
20773,12457.00,13062.00,-605.00


In [103]:
index = df_prueba[['salario_maximo','salario_minimo','Comprobacion_salario']][df_prueba['Comprobacion_salario'] < 0].index

In [104]:
df_prueba.drop(index, inplace=True)

In [105]:
(df_prueba['Comprobacion_salario'] < 0).sum()

0

In [106]:
df_glassdoor_procesado.drop(index, inplace=True)

# Adzuna

In [107]:
descripciones_adzuna = pd.read_json('../data/interim/extracion_descripcion_adzuna.jsonl', lines=True)
df_adzuna = pd.read_csv('../data/raw/AdzunaAPI_muestra.csv')

In [108]:
descripciones_adzuna = descripciones_adzuna.datos.apply(pd.Series)

In [109]:
descripciones_adzuna.head()

,años_experiencia,experiencia,modalidad,habilidades,formación_académica,sector,ciudad,tipo_de_empleo,beneficios
0,5.0,senior,None,"Ingeniería de Caminos, Canales y Puertos, segu...",Grado Universitario,Internet,Madrid,None,NaN
1,NaN,None,Remoto,"Java, AWS",Ninguna,Tecnología y telecomunicaciones,Madrid,None,NaN
2,5.0,senior,None,"OpenRTB, programmatic ecosystems, troubleshoot...",Ninguna,Tecnología y telecomunicaciones,Barcelona,None,NaN
3,NaN,None,None,"Mantenimiento preventivo y correctivo, cumplim...",Ninguna,Transporte y Logística,None,None,NaN
4,NaN,None,None,"Gestión de infraestructura IT, administración ...",Ninguna,Tecnología y telecomunicaciones,None,None,NaN


In [110]:
df_adzuna.head()

,redirect_url,created,description,__CLASS__,salary_max,id,category,title,adref,location,salary_min,company,salary_is_predicted,latitude,longitude,contract_time,contract_type
0,https://www.adzuna.es/land/ad/5512378982?se=wo...,2025-11-25T12:53:47Z,Una consultora de ingeniería y transporte en M...,Adzuna::API::Response::Job,125000.0,5512378982,"{'label': 'Trabajos en consultoría', '__CLASS_...",Líder de Proyectos Ferroviarios - Infraestruct...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTUxMjM3ODk4MiIsI...,"{'area': ['España', 'Comunidad de Madrid', 'Ma...",110000.0,"{'display_name': 'INECO', '__CLASS__': 'Adzuna...",0,40.4167,3.70325,NaN,NaN
1,https://www.adzuna.es/land/ad/5521450206?se=SF...,2025-12-01T13:01:00Z,Software Engineer Manager | Java & AWS | 100% ...,Adzuna::API::Response::Job,110000.0,5521450206,"{'tag': 'it-jobs', 'label': 'Trabajos en infor...",Software Engineer Manager | Java & AWS | 100% ...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiU0ZkVkFTclU4QkdNO...,"{'area': ['España', 'Comunidad de Madrid', 'Ma...",90000.0,{'__CLASS__': 'Adzuna::API::Response::Company'...,0,40.4167,3.70325,NaN,NaN
2,https://www.adzuna.es/land/ad/5530884914?se=cp...,2025-12-06T14:51:00Z,A dynamic product company in Barcelona is look...,Adzuna::API::Response::Job,110000.0,5530884914,"{'label': 'Trabajos en informática', 'tag': 'i...",Senior Solution Architect – AdTech & Data Plat...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiY3B4ZWVTX1U4QkduR...,"{'display_name': 'Barcelona, Cataluña', '__CLA...",90000.0,"{'display_name': 'Appodeal, Inc.', '__CLASS__'...",0,41.3851,2.17340,NaN,NaN
3,https://www.adzuna.es/details/5350502401?utm_m...,2025-08-13T15:25:15Z,"Coordinación de contratos, proveedores y presu...",Adzuna::API::Response::Job,50000.0,5350502401,"{'label': 'Trabajos en ingeniería', 'tag': 'en...",Jefe/a de Mantenimiento,eyJhbGciOiJIUzI1NiJ9.eyJzIjoicEd3QTR5YlU4QkdWd...,"{'area': ['España'], '__CLASS__': 'Adzuna::API...",45000.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN
4,https://www.adzuna.es/details/5291390409?utm_m...,2025-07-08T07:47:20Z,"Gestionar y mantener la infraestructura IT, as...",Adzuna::API::Response::Job,35000.0,5291390409,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...",Técnico de Infraestructuras IT,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5MTM5MDQwOSIsI...,"{'display_name': 'España', 'area': ['España'],...",28000.0,{'__CLASS__': 'Adzuna::API::Response::Company'},0,NaN,NaN,NaN,NaN


In [111]:
df_adzuna.shape, descripciones_adzuna.shape

((15000, 17), (15000, 9))

In [112]:
df_adzuna_procesado = pd.concat([df_adzuna, descripciones_adzuna], axis=1)

In [113]:
df_adzuna_procesado.head()

,redirect_url,created,description,__CLASS__,salary_max,id,category,title,adref,location,...,contract_type,años_experiencia,experiencia,modalidad,habilidades,formación_académica,sector,ciudad,tipo_de_empleo,beneficios
0,https://www.adzuna.es/land/ad/5512378982?se=wo...,2025-11-25T12:53:47Z,Una consultora de ingeniería y transporte en M...,Adzuna::API::Response::Job,125000.0,5512378982,"{'label': 'Trabajos en consultoría', '__CLASS_...",Líder de Proyectos Ferroviarios - Infraestruct...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTUxMjM3ODk4MiIsI...,"{'area': ['España', 'Comunidad de Madrid', 'Ma...",...,NaN,5.0,senior,None,"Ingeniería de Caminos, Canales y Puertos, segu...",Grado Universitario,Internet,Madrid,None,NaN
1,https://www.adzuna.es/land/ad/5521450206?se=SF...,2025-12-01T13:01:00Z,Software Engineer Manager | Java & AWS | 100% ...,Adzuna::API::Response::Job,110000.0,5521450206,"{'tag': 'it-jobs', 'label': 'Trabajos en infor...",Software Engineer Manager | Java & AWS | 100% ...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiU0ZkVkFTclU4QkdNO...,"{'area': ['España', 'Comunidad de Madrid', 'Ma...",...,NaN,NaN,None,Remoto,"Java, AWS",Ninguna,Tecnología y telecomunicaciones,Madrid,None,NaN
2,https://www.adzuna.es/land/ad/5530884914?se=cp...,2025-12-06T14:51:00Z,A dynamic product company in Barcelona is look...,Adzuna::API::Response::Job,110000.0,5530884914,"{'label': 'Trabajos en informática', 'tag': 'i...",Senior Solution Architect – AdTech & Data Plat...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiY3B4ZWVTX1U4QkduR...,"{'display_name': 'Barcelona, Cataluña', '__CLA...",...,NaN,5.0,senior,None,"OpenRTB, programmatic ecosystems, troubleshoot...",Ninguna,Tecnología y telecomunicaciones,Barcelona,None,NaN
3,https://www.adzuna.es/details/5350502401?utm_m...,2025-08-13T15:25:15Z,"Coordinación de contratos, proveedores y presu...",Adzuna::API::Response::Job,50000.0,5350502401,"{'label': 'Trabajos en ingeniería', 'tag': 'en...",Jefe/a de Mantenimiento,eyJhbGciOiJIUzI1NiJ9.eyJzIjoicEd3QTR5YlU4QkdWd...,"{'area': ['España'], '__CLASS__': 'Adzuna::API...",...,NaN,NaN,None,None,"Mantenimiento preventivo y correctivo, cumplim...",Ninguna,Transporte y Logística,None,None,NaN
4,https://www.adzuna.es/details/5291390409?utm_m...,2025-07-08T07:47:20Z,"Gestionar y mantener la infraestructura IT, as...",Adzuna::API::Response::Job,35000.0,5291390409,"{'tag': 'it-jobs', '__CLASS__': 'Adzuna::API::...",Técnico de Infraestructuras IT,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5MTM5MDQwOSIsI...,"{'display_name': 'España', 'area': ['España'],...",...,NaN,NaN,None,None,"Gestión de infraestructura IT, administración ...",Ninguna,Tecnología y telecomunicaciones,None,None,NaN


In [114]:
df_adzuna_procesado.columns

Index(['redirect_url', 'created', 'description', '__CLASS__', 'salary_max',
       'id', 'category', 'title', 'adref', 'location', 'salary_min', 'company',
       'salary_is_predicted', 'latitude', 'longitude', 'contract_time',
       'contract_type', 'años_experiencia', 'experiencia', 'modalidad',
       'habilidades', 'formación_académica', 'sector', 'ciudad',
       'tipo_de_empleo', 'beneficios'],
      dtype='object')

In [115]:
df_adzuna_procesado.drop(columns=['redirect_url','created','__CLASS__','id','category','adref','location','company','salary_is_predicted'
                                     ,'latitude','longitude','contract_time','contract_type','description'], inplace=True)

In [116]:
df_adzuna_procesado.head()

,salary_max,title,salary_min,años_experiencia,experiencia,modalidad,habilidades,formación_académica,sector,ciudad,tipo_de_empleo,beneficios
0,125000.0,Líder de Proyectos Ferroviarios - Infraestruct...,110000.0,5.0,senior,None,"Ingeniería de Caminos, Canales y Puertos, segu...",Grado Universitario,Internet,Madrid,None,NaN
1,110000.0,Software Engineer Manager | Java & AWS | 100% ...,90000.0,NaN,None,Remoto,"Java, AWS",Ninguna,Tecnología y telecomunicaciones,Madrid,None,NaN
2,110000.0,Senior Solution Architect – AdTech & Data Plat...,90000.0,5.0,senior,None,"OpenRTB, programmatic ecosystems, troubleshoot...",Ninguna,Tecnología y telecomunicaciones,Barcelona,None,NaN
3,50000.0,Jefe/a de Mantenimiento,45000.0,NaN,None,None,"Mantenimiento preventivo y correctivo, cumplim...",Ninguna,Transporte y Logística,None,None,NaN
4,35000.0,Técnico de Infraestructuras IT,28000.0,NaN,None,None,"Gestión de infraestructura IT, administración ...",Ninguna,Tecnología y telecomunicaciones,None,None,NaN


### Salario

In [117]:
df_adzuna_procesado['salary_min'] = df_adzuna_procesado['salary_min'].fillna(df_adzuna_procesado['salary_max'])
df_adzuna_procesado['salary_max'] = df_adzuna_procesado['salary_max'].fillna(df_adzuna_procesado['salary_min'])

In [118]:
df_prueba = df_adzuna_procesado.copy()
df_prueba['Comprobacion_salario'] = df_prueba['salary_max'] - df_prueba['salary_min']

In [119]:
(df_prueba['Comprobacion_salario'] < 0).sum()

0

En este caso no hay salarios máximos menores al salario mínimo.

In [120]:
df_adzuna_procesado.columns

Index(['salary_max', 'title', 'salary_min', 'años_experiencia', 'experiencia',
       'modalidad', 'habilidades', 'formación_académica', 'sector', 'ciudad',
       'tipo_de_empleo', 'beneficios'],
      dtype='object')

In [121]:
df_glassdoor_procesado.columns

Index(['Titulo', 'años_experiencia', 'experiencia', 'modalidad', 'habilidades',
       'formación_académica', 'salario_minimo', 'salario_maximo', 'sector',
       'tipo_de_empleo', 'beneficios', 'Ciudad'],
      dtype='object')

In [122]:
df_adzuna_procesado.rename(columns={'title':'Titulo', 'salary_min':'salario_minimo', 'salary_max':'salario_maximo',
                                    'ciudad':'Ciudad'}, inplace=True)

In [123]:
set(df_adzuna_procesado.columns) - set(df_glassdoor_procesado.columns)

set()

In [124]:
df_final = pd.concat([df_glassdoor_procesado, df_adzuna_procesado], ignore_index=True)

In [125]:
df_final.head()

,Titulo,años_experiencia,experiencia,modalidad,habilidades,formación_académica,salario_minimo,salario_maximo,sector,tipo_de_empleo,beneficios,Ciudad
0,FISIOTERAPEUTA NEUROLÓGICO,3.0,junior,Presencial,"Fisioterapia neurológica, habilidades de comun...",Grado Universitario,24000.0,26000.0,"Salud, Farmacia y Tecnología Médica",Media jornada,NaN,Madrid
1,Comercial puerta fría (presencial) - Sector ba...,2.0,junior,Presencial,"Comercialización, trabajo en equipo, habilidad...",Ninguna,14400.0,72000.0,Servicios,Jornada completa,NaN,Madrid
2,Profesora/a de Lengua 2ºESO (Aravaca),1.0,junior,Presencial,"Profesor, enseñanza, habilidades de comunicaci...",Grado Universitario,12000.0,14400.0,Economía y política,Jornada completa,NaN,Madrid
3,Direct Entry Captain - Pilot,3.0,senior,None,"Piloto, experiencia en Airbus FBW Wide Body, I...",Ninguna,131112.0,131112.0,Transporte y Logística,None,NaN,Madrid
4,Promotor/a - Encuestador/a de Educación (Campu...,0.0,intern,Presencial,"comunicación, empatía, atención al cliente, ca...",Ninguna,15120.0,15168.0,Economía y política,Jornada completa,NaN,Madrid


Voy ha hacer una limpieza de las columnas con texto (titulo, habilidades y beneficios)

In [126]:
# TITULO
# elimino () y lo que hay dentro (y espacios antes y después)
df_final['Titulo'] = df_final['Titulo'].str.replace(r'\s*\([^)]*\)', '', regex=True).str.strip()
# elimino caracteres especiales
df_final['Titulo'] = df_final['Titulo'].str.replace(r'\\W', '', regex=True)
# elimino espacios extra
df_final['Titulo'] = df_final['Titulo'].str.replace(r'\\s+', ' ', regex=True)

# Beneficios
# elimino caracteres especiales
df_final['beneficios'] = df_final['beneficios'].str.replace(r'\\W', '', regex=True).str.strip()
# elimino espacios extra
df_final['beneficios'] = df_final['beneficios'].str.replace(r'\\s+', ' ', regex=True)

# Habilidades
df_final['habilidades'] = df_final['habilidades'].str.replace(r'\\s+', ' ', regex=True).str.strip()
# no elimino caracteres especiales porque pueden ser parte de las habilidades (C++)

In [127]:
df_final.head()

,Titulo,años_experiencia,experiencia,modalidad,habilidades,formación_académica,salario_minimo,salario_maximo,sector,tipo_de_empleo,beneficios,Ciudad
0,FISIOTERAPEUTA NEUROLÓGICO,3.0,junior,Presencial,"Fisioterapia neurológica, habilidades de comun...",Grado Universitario,24000.0,26000.0,"Salud, Farmacia y Tecnología Médica",Media jornada,NaN,Madrid
1,Comercial puerta fría - Sector banca digital,2.0,junior,Presencial,"Comercialización, trabajo en equipo, habilidad...",Ninguna,14400.0,72000.0,Servicios,Jornada completa,NaN,Madrid
2,Profesora/a de Lengua 2ºESO,1.0,junior,Presencial,"Profesor, enseñanza, habilidades de comunicaci...",Grado Universitario,12000.0,14400.0,Economía y política,Jornada completa,NaN,Madrid
3,Direct Entry Captain - Pilot,3.0,senior,None,"Piloto, experiencia en Airbus FBW Wide Body, I...",Ninguna,131112.0,131112.0,Transporte y Logística,None,NaN,Madrid
4,Promotor/a - Encuestador/a de Educación,0.0,intern,Presencial,"comunicación, empatía, atención al cliente, ca...",Ninguna,15120.0,15168.0,Economía y política,Jornada completa,NaN,Madrid


In [128]:
df_final.shape

(36059, 12)

Voy a crear una columna de salario medio (media entre salario mínimo y máximo) y una columna de salarios categórica con un rango salarial. Esto para facilitar el EDA.

In [129]:
rangos = ["<15.000","15.000-22.000","22.000-30.000","30.000-40.000","40.000-52.000","52.000-65.000","65.000-80.000","80.000-100.000","100.000-150.000", ">150.000"]
df_final['Salario_medio'] = (df_final['salario_minimo'] + df_final['salario_maximo']) / 2
df_final['Rango_Salarial'] = pd.cut(df_final['Salario_medio'], bins=[0, 15000, 22000, 30000, 40000, 52000, 65000, 80000, 100000, 150000, float('inf')], labels=rangos)

Con esto ya no necesito las variables de salario mínimo y salario máximo.

In [130]:
df_final.drop(columns=['salario_minimo', 'salario_maximo'], inplace=True)

### Título y Habilidades

Voy a vectorizar las columas de título y habilidades para poder entrenar más adelante modelos con esta información. Voy a utilizar SBERT ya que es capaz de entender el contexto de cada palabra. Utilizó SBERT en lugar de BERT ya que este último tiene la capacidad de entender cada palabra individal de una frase dentro de su contexto mientras que SBERT genera un único vector para cada frase que representa su significado global, lo que facilita comparar miles de filas rápidamente.

In [131]:
# Primero genero una columna única para título y habilidades.
df_final['Titulo_Habilidades'] = df_final['Titulo'] + ' ' + df_final['habilidades']

# Limpiar cadenas
df_final['Titulo_Habilidades'] = df_final['Titulo_Habilidades'].astype(str).str.strip()
df_final['Titulo_Habilidades'] = df_final['Titulo_Habilidades'].str.lower()

# guardo los textos preparados en una lista para generar los embeddings
textos = ["passage: " + texto for texto in df_final['Titulo_Habilidades'].tolist()] 
#passage es necesario para que el modelo de embeddings sepa que es un texto a procesar

In [56]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('intfloat/multilingual-e5-large', device='cuda') #cargar el modelo SBERT (acorde a mi tarjeta gráfica de los que mejor funciona)

# Generar los embeddings para los textos 
matriz_embeddings = model.encode(
    textos, 
    show_progress_bar=True, 
    batch_size=64 
)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/564 [00:00<?, ?it/s]

In [132]:
print(len(matriz_embeddings[0]))

1024


Ahora voy a aplicar PCA para reducir las 1024 dimensiones en 15-20.

In [ ]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(matriz_embeddings)

#Calcular la varianza explicada acumulada
varianza_acumulada = np.cumsum(pca.explained_variance_ratio_)

# Determinar el número de componentes necesarios para explicar al menos el 85% de la varianza
n_componentes = np.argmax(varianza_acumulada >= 0.85) + 1
print(n_componentes)

171


Puedo reducir el número de dimensiones a 171 y mantener un 85% de la varianza explicada. 

In [133]:
pca = PCA(n_components=171, random_state=42)
embeddings_reducidos = pca.fit_transform(matriz_embeddings)
df_embeddings = pd.DataFrame(embeddings_reducidos, columns=[f'PC{i+1}' for i in range(embeddings_reducidos.shape[1])])
df_embeddings.head()

,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC162,PC163,PC164,PC165,PC166,PC167,PC168,PC169,PC170,PC171
0,0.004224,0.053959,-0.031149,-0.036298,0.013103,-0.038561,0.108334,-0.010143,0.027395,-0.042883,...,-0.007727,-0.009880,-0.010779,-0.015018,-0.012049,-0.000468,-0.002677,0.015551,0.002135,0.012447
1,0.069272,0.000184,-0.141946,0.037959,-0.043406,-0.033353,0.022051,0.041757,-0.023587,0.027368,...,-0.016688,0.009373,0.009987,0.006272,-0.004468,0.004384,-0.023007,0.021068,-0.008933,-0.009431
2,-0.187580,0.058792,-0.023347,-0.030711,-0.070049,-0.017177,0.069038,-0.022394,0.058939,0.008333,...,-0.005598,-0.005655,-0.021037,-0.007808,0.019000,0.017870,-0.007603,0.025131,0.007499,0.016103
3,-0.095188,-0.053940,0.001271,0.066089,-0.016740,0.045195,0.029415,0.067742,0.030068,0.017823,...,0.035486,-0.002829,-0.009639,-0.023406,-0.009968,0.014027,-0.023674,0.010536,0.022368,0.001043
4,-0.184019,0.030609,-0.057100,-0.041649,-0.071965,-0.015309,-0.035196,-0.005309,0.011208,0.028371,...,0.001686,0.006564,0.009963,0.009632,-0.014727,0.009890,-0.000782,0.047213,-0.019073,0.009518


In [136]:
# Voy a generar un id común para cada fila de df_final y df_embeddings para poder unirlos posteriormente
df_final['id'] = df_final.index
df_embeddings['id'] = df_embeddings.index

In [138]:
df_final.drop(columns=['Titulo', 'habilidades','Titulo_Habilidades'], inplace=True)

In [139]:
df_final.to_csv('../data/interim/df_merged.csv', index=False)
df_embeddings.to_csv('../data/interim/df_embeddings.csv', index=False)